apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhilhealth
spec:
  selector:
    matchLabels:
      app: akhilhealth
  replicas: 3
  template:
    metadata:
      labels:
        app: akhilhealth
    spec:
      containers:
      - name: healthcontainer
        image: akhil2598/healthcare-project:1.0
        imagePullPolicy: Always
        ports:
        - name: akhilhealth
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: healthservice
  labels:
    app: akhilhealth
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8086
  selector:
    app: akhilhealth
